name: liri-platform-0-9
version: script
version-script: |
  echo $(date '+%Y%m%d')-$(git rev-parse --short HEAD)
summary: Liri Platform for sharing common libraries used by Liri products
description: |
  The Liri Platform provides a set of libraries that can be used by
  Liri's cross-platform apps in order to minimize the disk space usage.
grade: devel
confinement: strict
architectures: [amd64]

slots:
  platform:
    content: liri-platform
    interface: content
    read: [.]

apps:
  fluid-demo:
    command: liri-app-launch "fluid-demo"
    plugs:
      - x11
      - opengl
      - unity7

parts:
  liri-app-launch:
    source: src
    plugin: dump
    organize:
      liri-app-launch.sh: bin/liri-app-launch
    stage:
      - bin/liri-app-launch
    after:
      - desktop-glib-only
  liri-qbs-meta: &liri-qbs-meta
    plugin: template
    build-attributes: ["no-system-libraries"]
    qbs-options:
      - modules.lirideployment.prefix:usr
      - modules.lirideployment.qmlDir:usr/lib/x86_64-linux-gnu/qt5/qml
      - modules.lirideployment.pluginsDir:usr/lib/x86_64-linux-gnu/qt5/plugins
  fluid:    
    <<: *liri-qbs-meta
    source: https://github.com/lirios/fluid.git
    plugin: qbs
    qbs-options:
      - modules.lirideployment.prefix:usr
      - modules.lirideployment.qmlDir:usr/lib/x86_64-linux-gnu/qt5/qml
      - modules.lirideployment.pluginsDir:usr/lib/x86_64-linux-gnu/qt5/plugins
      - projects.Fluid.useSystemQbsShared:true
    after:
      - qt
      - qbs
  qtaccountsservice:
    <<: *liri-qbs-meta
    plugin: qbs
    source: https://github.com/lirios/qtaccountsservice.git
    after:
      - qt
      - qbs
      - qbs-shared
  qtgsettings:
    <<: *liri-qbs-meta
    plugin: qbs
    source: https://github.com/lirios/qtgsettings.git
    build-packages:
      - libglib2.0-dev
    after:
      - qt
      - qbs
  libliri:
    <<: *liri-qbs-meta
    plugin: qbs
    source: https://github.com/lirios/libliri.git
    after:
      - qbs
      - qbs-shared
      - libqtxdg
  liri-wayland:
    <<: *liri-qbs-meta
    plugin: qbs
    source: https://github.com/lirios/wayland.git
    build-packages:
      - libudev-dev
      - libinput-dev
      - libgbm1
      - libgbm-dev
      - libxcb-cursor-dev
      - libxcb-cursor0
      - libxcb-composite0-dev
      - libxcb-composite0
      - libwayland-client0
      - libwayland-dev
      - libx11-dev
      - libxcursor-dev
      - libx11-xcb-dev
      - libegl1-mesa-dev
    stage-packages:
      - libudev1
      - libinput10
    after:
      - qt
      - qbs
      - qbs-shared
      - kf5-deps
      - libliri
      - qtwayland
  vibe:
    <<: *liri-qbs-meta
    plugin: qbs
    source: https://github.com/lirios/vibe.git
    build-packages:
      - libpolkit-qt5-1-dev
      - libpolkit-qt5-1-1
      - libpulse-dev
      - libpulse0
      - libdrm-dev
      - libgbm-dev
      - libxcb-cursor-dev
    stage-packages:
      - libpolkit-qt5-1-dev
      - libpolkit-qt5-1-1
      - libpulse-dev
      - libpulse0
      - libdrm2
      - libxcb-cursor0
    after:
      - qt
      - kf5-deps
      - qbs
      - qbs-shared
      - libliri
      - fluid
  qbs-shared:
    plugin: qbs
    source: https://github.com/lirios/qbs-shared.git
    qbs-options:
      - project.prefix:usr
    after:
      - qt
      - qbs
  fonts:
    plugin: nil
    stage-packages:
      - fonts-roboto
      - fonts-noto
  libqtxdg:
    plugin: cmake
    source: https://github.com/lxde/libqtxdg/archive/2.0.0.tar.gz
    after: [qt]
  # As of 2018-03-31, Debian is lacking private headers for QtWayland
  # (in libqt5waylandclient5-dev).
  # Therefore we build this module from source as a workaround.
  # See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894472
  qtwayland:
    plugin: qmake
    source: https://github.com/qt/qtwayland.git
    source-tag: v5.10.0
    after: [qt]
    build-packages:
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxkbcommon-dev
      - libwayland-dev
      - libdrm-dev
    stage-packages:
      - libwayland-cursor0
  qbs:
    plugin: nil
    stage-packages:
      - qbs
      - qbs-dev
    after: [qt]
  kf5-deps:
    plugin: nil
    build-packages:
      - modemmanager-dev
      - network-manager-dev
      - libmm-glib-dev
      - libnm-dev
      - modemmanager
      - network-manager
    stage-packages:
      - libkf5solid5
      - libkf5solid-dev 
      - libkf5networkmanagerqt-dev
      - modemmanager-qt-dev
      - libkf5networkmanagerqt6
      - libkf5modemmanagerqt6
      - modemmanager-dev
      - network-manager-dev
      - modemmanager
      - network-manager
      - libmm-glib-dev
      - libnm-dev
    after:
      - qt
      - qt-conf-bin
      - qt-conf-libexec
  qt-conf-bin:
    plugin: dump
    source: src
    organize:
      qt.conf: usr/lib/x86_64-linux-gnu/qt5/bin/qt.conf
    stage:
      - usr/lib/x86_64-linux-gnu/qt5/bin/qt.conf
    after: [qt]
  qt-conf-libexec:
    plugin: dump
    source: src
    organize:
      qt.conf: usr/lib/x86_64-linux-gnu/qt5/libexec/qt.conf
    stage:
      - usr/lib/x86_64-linux-gnu/qt5/libexec/qt.conf
    after: [qt]
  qt-symlinks:
    plugin: nil
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/qt5
      ln -s ../../../share/qt5/translations \
        $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/qt5/translations
      ln -s ../../../share/qt5/resources \
        $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/qt5/resources
    after: [qt]
  qt:
    plugin: nil
    stage-packages:
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtbase5-private-dev
      - libqt5opengl5-dev
      - libqt5opengl5
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtdeclarative5-private-dev
      - qtquickcontrols2-5-dev
      - libqt5svg5-dev
      - libqt5webengine5
      - qtwebengine5-dev
      - qtwebengine5-dev-tools
      - qttools5-dev
      - qttools5-dev-tools
      - qttools5-private-dev
      - qml-module-qtquick2
      - qml-module-qtquick-window2
      - qml-module-qtquick-layouts
      - qml-module-qttest
      - qml-module-qtgraphicaleffects
      - qml-module-qtqml-models2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-templates2
      - qml-module-qt-labs-platform
      - qml-module-qt-labs-calendar
      - qml-module-qtwebengine
      - qml-module-qtwebchannel
