name: liri-platform0
version: '0.10.0'
summary: Liri Platform for sharing common libraries used by Liri products
description: |
    The Liri Platform provides a set of libraries that can be used by
    Liri's cross-platform apps in order to minimize the disk space usage.
grade: devel
confinement: strict

slots:
    platform:
        content: liri-platform0
        interface: content
        read: [.]

apps:
    fluid-demo:
        command: liri-app-launch "fluid-demo"
        plugs:
            - x11
            - opengl
            - unity7

    fluid-dialog:
        command: liri-app-launch "fluid-dialog"
        plugs:
            - x11
            - opengl
            - unity7

parts:
    # Liri App Launcher
    liri-app-launch:
        source: src
        plugin: dump
        organize:
            liri-app-launch.sh: bin/liri-app-launch
    # Fluid Dialog
    fluid-dialog:
        source: src/fluid-dialog
        plugin: qmake
        qt-version: qt5
        after: [qt, fluid]
    # Fluid (http://github.com/lirios/fluid)
    fluid:
        source: https://github.com/lirios/fluid
        source-branch: v0.10.0 # develop
        source-type: git
        plugin: cmake
        build-packages: 
            - extra-cmake-modules
        configflags: 
            - -DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/lib/qt5/lib/cmake/
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/
            - -DCMAKE_INSTALL_LIBDIR=lib/qt5/lib
            - -DKDE_INSTALL_QMLDIR=/lib/qt5/qml
            - -DECM_DIR=/usr/share/ECM/cmake
        build-attributes: ["no-system-libraries"]        
        prepare: |
            # Change directory to ../src
            # because cmake plugin wipes out
            # build entirely before actually
            # building.
            cd ../src
            ./scripts/fetch_icons.sh
        after: [qt]
    # CLI YAML parser written in go
    # https://github.com/mikefarah/yaml
    # Made by Mike Farah (@mikefarah)
    # MIT licensed
    yaml-cli:
        source: https://github.com/mikefarah/yaml
        source-type: git
        source-tag: "1.6"
        plugin: go
    # Qt
    # based on https://github.com/tjyrinki/qt58
    # Thanks to Timo Jyrinki (@tjyrinki)
    qt:
        plugin: autotools
        source-type: git
        source: https://code.qt.io/qt/qt5.git
        source-branch: "v5.8.0"
        build-attributes: ["no-system-libraries"]
        after: [qt-dependencies]
        configflags:        # config flags: for arm64, -opengl es2 platform linux-g++
            - -prefix
            - $SNAPCRAFT_PART_INSTALL/lib/qt5
            - -bindir
            - $SNAPCRAFT_PART_INSTALL/usr/bin
            - -release
            #        - -libdir $SNAP/lib
            #        - -docdir $SNAP/doc
            #        - -headerdir $SNAP/include
            #        - -datadir $SNAP/share
            #        - -archdatadir $SNAP/lib
            #        - -hostdatadir $SNAP/share
            #        - -plugindir $SNAP/lib/plugins
            #        - -importdir $SNAP/lib/imports
            #        - -translationdir $SNAP/share/translations
            #        - -hostdatadir $SNAP/lib
            #        - -sysconfdir $SNAP/etc/xdg
            #        - -examplesdir $SNAP/lib/examples
            - -confirm-license
            - -opensource
            - -plugin-sql-mysql
            - -plugin-sql-odbc
            - -plugin-sql-psql
            - -plugin-sql-sqlite
            - -no-sql-sqlite2
            - -plugin-sql-tds
            - -system-sqlite
            - -platform
            - linux-g++-64
            - -system-harfbuzz
            - -system-zlib
            - -system-libpng
            - -system-libjpeg
            - -openssl
            - -no-rpath
            - -verbose
            - -optimized-qmake
            - -dbus-linked
            #- -no-strip
            - -strip
            #- -no-separate-debug-info
            - -qpa
            - xcb
            - -xcb
            - -glib
            - -icu
            - -accessibility
            - -no-compile-examples
            - -no-directfb
            - -gstreamer
            - "1.0"
            - -opengl
            - desktop
            - -nomake
            - examples
            - -nomake
            - tests
            - -skip
            - qtquick1
            - -skip
            - qtwayland
            - -skip
            - qtwebengine
            - -skip
            - qtwebview
            - -skip
            - qtwebkit
            - -skip
            - qtwebkit-examples
    # Qt dependencies
    qt-dependencies:
        plugin: dump
        # From deb packaging build deps
        build-packages:
            - g++
#               - debhelper
#               - dpkg-dev
            - freetds-dev
            - gdb
            - libasound2-dev
            - libatspi2.0-dev
            - libcups2-dev
            - libdbus-1-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgbm-dev
            - libgl1-mesa-dev
            - libgles2-mesa-dev
            - libglib2.0-dev
            - libglu1-mesa-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libgtk2.0-dev
            - libharfbuzz-dev
            - libicu-dev
            - libinput-dev
            - libjpeg-dev
            - libmtdev-dev
            - libmysqlclient-dev
            - libpcre3-dev
            - libpng12-dev
            - libpq-dev
            - libproxy-dev
            - libpulse-dev
            - libsqlite3-dev
            - libssl-dev
            - libudev-dev
            - libx11-dev
            - libx11-xcb-dev
            - libxcb-icccm4-dev
            - libxcb-image0-dev
            - libxcb-keysyms1-dev
            - libxcb-randr0-dev
            - libxcb-render-util0-dev
            - libxcb-render0-dev
            - libxcb-shape0-dev
            - libxcb-shm0-dev
            - libxcb-sync-dev
            - libxcb-xfixes0-dev
            - libxcb-xinerama0-dev
            - libxcb-xkb-dev
            - libxcb1-dev
            - libxext-dev
            - libxi-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - libxrender-dev
            - pkg-kde-tools
            - publicsuffix
            - unixodbc-dev
            - xvfb
            - zlib1g-dev
        # currently tailored from ubuntu 16.04 package names (mostly libpng etc may vary)
        stage-packages:
            - etc1tool # minimal package for depending on libpng regardless of Ubuntu version
            - fontconfig
            - icu-devtools
            - libc6
            - libcups2
            - libdbus-1-3
            - libdrm2
            - libegl1-mesa
            - libfontconfig1
            - libfreetype6
            - libgbm1
            - libgcc1
            - libgl1-mesa-dev
            - libgl1-mesa-glx
            - libgles2-mesa-dev
            - libglib2.0-0
            - libglu1-mesa-dev
            - libharfbuzz0b
            - libice6
            - libinput10
            - libjpeg8
            - libmtdev1
            - libpcre16-3
            - libproxy1v5
            - libsm6
            - libsqlite3-0
            - libstdc++6
            - libudev1
            - libx11-6
            - libx11-xcb1
            - libxcb1
            - libxcb-glx0
            - libxcb-icccm4
            - libxcb-image0
            - libxcb-keysyms1
            - libxcb-randr0
            - libxcb-render0
            - libxcb-render-util0
            - libxcb-shape0
            - libxcb-shm0
            - libxcb-sync1
            - libxcb-xfixes0
            - libxcb-xkb1
            - libxext-dev
            - libxi6
            - libxkbcommon0
            - libxkbcommon-x11-0
            - libxcb-xinerama0
            - libxrender1
            - perl
            - zlib1g
            - libdouble-conversion1v5
            - libpulse0

